piVersion: v1
kind: Service
metadata:
  labels:
    app: yuki-nakayama-live-pfs
    app.kubernetes.io/instance: yuki-nakayama-live-pfs
    app.kubernetes.io/name: yuki-nakayama-live-pfs
  name: yuki-nakayama-live-pfs
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: yuki-nakayama-live-pfs
    app.kubernetes.io/name: yuki-nakayama-live-pfs
  sessionAffinity: None
  type: ClusterIP